services:
  nginx:
    image: nginx:alpine
    container_name: dima-site
    restart: always
    networks:
      - web-proxy
    volumes:
      # This matches your GitHub Action target exactly
      - /var/www/dombotsite/browser:/usr/share/nginx/html:ro
      # Mounts the config file from the current directory
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro

networks:
  web-proxy:
    external: true